export { default as AppButton }      from './components/Button.vue'
export { default as AppCard }        from './components/Card.vue'
export { default as AppBadge }       from './components/Badge.vue'
export { default as AppModal }       from './components/Modal.vue'
export { default as AppInput }       from './components/Input.vue'
export { default as AppSpinner }     from './components/Spinner.vue'
export { default as ToastContainer } from './components/ToastContainer.vue'
export { default as EmptyState }     from './components/EmptyState.vue'
export { default as ConfirmDialogContainer } from './components/ConfirmDialogContainer.vue'
export { default as LoginView }      from './views/LoginView.vue'
export { useToast } from './composables/useToast'
export { useConfirm } from './composables/useConfirm'

// Design System — Phase 2 component library. See CLAUDE.md / wagdy.md for
// the full plan; these are additive-only (no existing screen imports them
// yet — that migration is a deliberate later stage).
export { default as AppIcon }        from './components/Icon.vue'
export type { IconName } from './icons/registry'
export { default as IconButton }     from './components/IconButton.vue'
export { default as AppTextarea }    from './components/Textarea.vue'
export { default as AppSelect }      from './components/Select.vue'
export type { SelectOption } from './components/Select.vue'
export { default as SearchInput }    from './components/SearchInput.vue'
export { default as MoneyInput }     from './components/MoneyInput.vue'
export { default as PhoneInput }     from './components/PhoneInput.vue'
export { default as DatePicker }     from './components/DatePicker.vue'
export { default as TimePicker }     from './components/TimePicker.vue'
export { default as StatCard }       from './components/StatCard.vue'
export { default as ErrorState }     from './components/ErrorState.vue'
export { default as LoadingState }   from './components/LoadingState.vue'
export { default as Skeleton }       from './components/Skeleton.vue'
export { default as AppAvatar }      from './components/Avatar.vue'
export { default as StatusBadge }    from './components/StatusBadge.vue'
export { default as RoleBadge }      from './components/RoleBadge.vue'
export { default as PermissionBadge } from './components/PermissionBadge.vue'
export { default as AppDrawer }      from './components/Drawer.vue'
export { default as AppTabs }        from './components/Tabs.vue'
export type { TabItem } from './components/Tabs.vue'
export { default as AppAccordion }   from './components/Accordion.vue'
export { default as AppTimeline }    from './components/Timeline.vue'
export type { TimelineItem } from './components/Timeline.vue'
export { default as AppProgress }    from './components/Progress.vue'
export { default as Paginator }      from './components/Paginator.vue'
export { default as FloatingActionButton } from './components/FloatingActionButton.vue'
export { default as Dropdown }       from './components/Dropdown.vue'
export { default as DataTable }      from './components/DataTable.vue'
export type { DataTableColumn } from './components/DataTable.vue'
export { default as ThemeToggle }    from './components/ThemeToggle.vue'

// Design System — Phase 2: المكونات الـ 7 الجديدة (2026-07-14)
export { default as ChartWrapper }   from './components/ChartWrapper.vue'
export type { ChartDataset, ChartType } from './components/ChartWrapper.vue'
export { default as FiltersPanel }   from './components/FiltersPanel.vue'
export type { FilterField, FilterFieldType } from './components/FiltersPanel.vue'
export { default as Combobox }       from './components/Combobox.vue'
export type { ComboboxOption } from './components/Combobox.vue'
export { default as Autocomplete }   from './components/Autocomplete.vue'
export type { AutocompleteSuggestion } from './components/Autocomplete.vue'
export { default as Wizard }         from './components/Wizard.vue'
export type { WizardStep } from './components/Wizard.vue'
export { default as CommandPalette } from './components/CommandPalette.vue'
export type { CommandItem } from './components/CommandPalette.vue'
export { default as VirtualTable }   from './components/VirtualTable.vue'
export type { VirtualTableColumn } from './components/VirtualTable.vue'
