// All API endpoints — mirrors backend routes
export const ENDPOINTS = {
  auth: {
    login: '/api/v1/auth/login',
    logout: '/api/v1/auth/logout',
    refresh: '/api/v1/auth/refresh',
    me: '/api/v1/auth/me',
    // Gate 3A — self-service personal preferences (staff display language).
    mePreferences: '/api/v1/auth/me/preferences',
    changePassword: '/api/v1/auth/change-password',
    setup2fa: '/api/v1/auth/2fa/setup',
    enable2fa: '/api/v1/auth/2fa/enable',
    disable2fa: '/api/v1/auth/2fa/disable',
    regenerateRecoveryCodes: '/api/v1/auth/2fa/recovery-codes/regenerate',
    passwordResetRequest: '/api/v1/auth/password-reset/request',
    passwordResetConfirm: '/api/v1/auth/password-reset/confirm',
    // Gate 2B3A — step-up control plane (docs/decisions/0003-super-admin-control-plane.md)
    stepUp: '/api/v1/auth/step-up',
    // Gate 2B3B — session & security self-service. Single-session DELETE builds
    // its URL as `${ENDPOINTS.auth.sessions}/${ref}` (step-up token required).
    sessions: '/api/v1/auth/sessions',
    sessionsRevokeOthers: '/api/v1/auth/sessions/revoke-others',
    securityActivity: '/api/v1/auth/security-activity',
  },
  core: {
    branches: '/api/v1/branches',
    notifications: '/api/v1/notifications',
    // Guest alerts (نادِ الجرسون / هات الفاتورة) — راجع
    // backend/app/modules/core/models.py::GuestAlert
    alerts: '/api/v1/alerts',
    alertStatus: (alertId: number) => `/api/v1/alerts/${alertId}/status`,
    // WebSocket — بث لحظي لتنبيهات الضيوف (نفس نمط kdsWs في dining)
    alertsWs: (branchId: number) => `/api/v1/ws/alerts/${branchId}`,
    // PIN تشغيلي — راجع backend/app/modules/core/models.py::PinCredential
    pinApprovers: '/api/v1/pins/approvers',
    pinSwitch: '/api/v1/pins/switch',
  },
  beach: {
    inventory: '/api/v1/beach/inventory',
    summary: '/api/v1/beach/summary',
    sell: '/api/v1/beach/sell',
    transactions: '/api/v1/beach/transactions',
    ticket: (txId: number) => `/api/v1/beach/transactions/${txId}/ticket`,
    b2bContracts: '/api/v1/beach/b2b-contracts',
    b2bContract: (id: number) => `/api/v1/beach/b2b-contracts/${id}`,
    b2bContractSettle: (id: number) => `/api/v1/beach/b2b-contracts/${id}/settle`,
    b2bCheckin: '/api/v1/beach/b2b-checkin',
    surge: '/api/v1/beach/surge',
    transactionVoid: (id: number) => `/api/v1/beach/transactions/${id}/void`,
    reservations: '/api/v1/beach/reservations',
    reservationPublic: (id: number) => `/api/v1/beach/reservations/${id}/public`,
    reservationCheckin: (id: number) => `/api/v1/beach/reservations/${id}/checkin`,
    b2bQuotaStatus: '/api/v1/beach/b2b-contracts/status',
    liveDashboard: '/api/v1/beach/live-dashboard',
    eodReport: '/api/v1/beach/eod-report',
    eodReportPdf: '/api/v1/beach/eod-report/pdf',
    // خريطة الشاطئ الحية (شمسية/برجولة فعلية) — راجع
    // backend/app/modules/beach/models.py::BeachLocation
    locations: '/api/v1/beach/locations',
    locationsBulk: '/api/v1/beach/locations/bulk',
    locationsReduce: '/api/v1/beach/locations/reduce',
    locationUpdate: (id: number) => `/api/v1/beach/locations/${id}`,
    locationCheckin: (id: number) => `/api/v1/beach/locations/${id}/checkin`,
    locationCheckout: (id: number) => `/api/v1/beach/locations/${id}/checkout`,
  },
  // Unified dining module — replaced the old separate restaurant:/cafe:
  // blocks entirely (DINING_CUTOVER_PLAN.md Batch 6, 2026-07-13). outlet_id-
  // scoped paths mirror app/modules/dining/api/router.py exactly.
  dining: {
    outlets: '/api/v1/dining/outlets',
    outlet: (outletId: number) => `/api/v1/dining/outlets/${outletId}`,
    categories: (outletId: number) => `/api/v1/dining/outlets/${outletId}/categories`,
    category: (categoryId: number) => `/api/v1/dining/categories/${categoryId}`,
    items: (outletId: number) => `/api/v1/dining/outlets/${outletId}/items`,
    item: (itemId: number) => `/api/v1/dining/items/${itemId}`,
    extraGroups: (itemId: number) => `/api/v1/dining/items/${itemId}/extra-groups`,
    extraGroup: (groupId: number) => `/api/v1/dining/extra-groups/${groupId}`,
    variants: (itemId: number) => `/api/v1/dining/items/${itemId}/variants`,
    variant: (variantId: number) => `/api/v1/dining/variants/${variantId}`,
    recipeLines: (itemId: number) => `/api/v1/dining/items/${itemId}/recipe-lines`,
    recipeLine: (lineId: number) => `/api/v1/dining/recipe-lines/${lineId}`,
    variantRecipeLines: (variantId: number) => `/api/v1/dining/variants/${variantId}/recipe-lines`,
    variantRecipeLine: (lineId: number) => `/api/v1/dining/variant-recipe-lines/${lineId}`,
    itemImage: (itemId: number) => `/api/v1/dining/items/${itemId}/image`,
    // الطاولة مشتركة بين كل منافذ الفرع (2026-07-21) — مش outlet-scoped
    // بعد كده، راجع backend's VenueTable docstring.
    tables: (branchId: number) => `/api/v1/dining/branches/${branchId}/tables`,
    table: (tableId: number) => `/api/v1/dining/tables/${tableId}`,
    tableGrid: (tableId: number) => `/api/v1/dining/tables/${tableId}/grid`,
    orders: '/api/v1/dining/orders',
    order: (orderId: number) => `/api/v1/dining/orders/${orderId}`,
    outletOrders: (outletId: number) => `/api/v1/dining/outlets/${outletId}/orders`,
    outletOrdersHold: (outletId: number) => `/api/v1/dining/outlets/${outletId}/orders/hold`,
    outletOrdersHeld: (outletId: number) => `/api/v1/dining/outlets/${outletId}/orders/held`,
    orderItems: (orderId: number) => `/api/v1/dining/orders/${orderId}/items`,
    orderItemVoid: (orderId: number, itemId: number) => `/api/v1/dining/orders/${orderId}/items/${itemId}/void`,
    orderItemRefund: (orderId: number, itemId: number) => `/api/v1/dining/orders/${orderId}/items/${itemId}/refund`,
    orderItemStatus: (orderId: number, itemId: number) => `/api/v1/dining/orders/${orderId}/items/${itemId}/status`,
    orderStatus: (orderId: number) => `/api/v1/dining/orders/${orderId}/status`,
    orderTransfer: (orderId: number) => `/api/v1/dining/orders/${orderId}/transfer`,
    orderDiscount: (orderId: number) => `/api/v1/dining/orders/${orderId}/discount`,
    orderSplitBill: (orderId: number) => `/api/v1/dining/orders/${orderId}/split-bill`,
    orderMerge: (orderId: number) => `/api/v1/dining/orders/${orderId}/merge`,
    receipt: (orderId: number) => `/api/v1/dining/orders/${orderId}/receipt`,
    kitchenTickets: '/api/v1/dining/kitchen/tickets',
    ticketStatus: (ticketId: number) => `/api/v1/dining/kitchen/tickets/${ticketId}/status`,
    kdsWs: (branchId: number) => `/api/v1/dining/ws/kds/${branchId}`,
    kdsScreens: '/api/v1/dining/kds-screens',
    kdsScreen: (id: number) => `/api/v1/dining/kds-screens/${id}`,
    tablesWs: (branchId: number) => `/api/v1/dining/ws/tables/${branchId}`,
    salesReport: (outletId: number) => `/api/v1/dining/outlets/${outletId}/reports/sales`,
    foodCostReport: (outletId: number) => `/api/v1/dining/outlets/${outletId}/reports/food-cost`,
    foodCostReportAll: '/api/v1/dining/reports/food-cost',
  },
  finance: {
    // WebSocket — بث لحظي لمدير+ لما دفعة ترتبط بوردية مفتوحة (بيع شاطئ
    // مباشر أو تسوية فوليو)، نفس نمط kdsWs/alertsWs — إشارة "أعد تحميل
    // تفاصيل الوردية"، مفيش بيانات مالية جوه رسالة الـ WS نفسها.
    shiftsWs: (branchId: number) => `/api/v1/finance/ws/shifts/${branchId}`,
    accounts: '/api/v1/finance/accounts',
    checks: '/api/v1/finance/checks',
    checkStatus: (id: number) => `/api/v1/finance/checks/${id}/status`,
    periods: '/api/v1/finance/periods',
    periodClose: (y: number, m: number) => `/api/v1/finance/periods/${y}/${m}/close`,
    folios: '/api/v1/finance/folios',
    folio: (id: number) => `/api/v1/finance/folios/${id}`,
    folioCharges: (id: number) => `/api/v1/finance/folios/${id}/charges`,
    folioPayments: (id: number) => `/api/v1/finance/folios/${id}/payments`,
    folioSettle: (id: number) => `/api/v1/finance/folios/${id}/settle`,
    folioStatementPdf: (id: number) => `/api/v1/finance/folios/${id}/statement/pdf`,
    shiftsOpen: '/api/v1/finance/shifts/open',
    shiftsCurrent: '/api/v1/finance/shifts/current',
    shifts: '/api/v1/finance/shifts',
    shiftReport: (id: number) => `/api/v1/finance/shifts/${id}/report`,
    shiftReportPdf: (id: number) => `/api/v1/finance/shifts/${id}/report/pdf`,
    shiftInvoices: (id: number) => `/api/v1/finance/shifts/${id}/invoices`,
    shiftClose: (id: number) => `/api/v1/finance/shifts/${id}/close`,
    shiftHandoverNote: '/api/v1/finance/shifts/handover-note',
    shiftCashMovements: (id: number) => `/api/v1/finance/shifts/${id}/cash-movements`,
    costCenters: '/api/v1/finance/cost-centers',
    costCenterReport: '/api/v1/finance/cost-centers/report',
    discounts: '/api/v1/finance/discounts',
    discount: (id: number) => `/api/v1/finance/discounts/${id}`,
    calculateDiscount: '/api/v1/finance/calculate-discount',
    exchangeRates: '/api/v1/finance/exchange-rates',
    journalEntries: '/api/v1/finance/journal-entries',
    journalEntry: (id: number) => `/api/v1/finance/journal-entries/${id}`,
    reportsTrialBalance: '/api/v1/finance/reports/trial-balance',
    reportsIncomeStatement: '/api/v1/finance/reports/income-statement',
    reportsBalanceSheet: '/api/v1/finance/reports/balance-sheet',
    paymentVoid: (id: number) => `/api/v1/finance/payments/${id}/void`,
    revenueAuditLogs: '/api/v1/finance/revenue-audit-logs',
    bankAccounts: '/api/v1/finance/bank-accounts',
    bankAccount: (id: number) => `/api/v1/finance/bank-accounts/${id}`,
    bankAccountStatementLines: (id: number) => `/api/v1/finance/bank-accounts/${id}/statement-lines`,
    bankAccountAutoMatch: (id: number) => `/api/v1/finance/bank-accounts/${id}/statement-lines/auto-match`,
    bankAccountReconciliationSummary: (id: number) => `/api/v1/finance/bank-accounts/${id}/reconciliation-summary`,
    depreciationEntries: '/api/v1/finance/depreciation/entries',
    depreciationRun: '/api/v1/finance/depreciation/run',
    etaInvoices: '/api/v1/finance/eta/invoices',
    etaInvoice: (id: number) => `/api/v1/finance/eta/invoices/${id}`,
  },
  hr: {
    employees: '/api/v1/hr/employees',
    employee: (id: number) => `/api/v1/hr/employees/${id}`,
    employeeAllowances: (id: number) => `/api/v1/hr/employees/${id}/allowances`,
    employeePayslip: (id: number) => `/api/v1/hr/employees/${id}/payslip`,
    employeeLinkUser: (id: number) => `/api/v1/hr/employees/${id}/link-user`,
    payroll: '/api/v1/hr/payroll/runs',
    payrollRunLines: (id: number) => `/api/v1/hr/payroll-runs/${id}/lines`,
    payrollRunApprove: (id: number) => `/api/v1/hr/payroll-runs/${id}/approve`,
    payrollRunExcel: (id: number) => `/api/v1/hr/payroll/${id}/excel`,
    payrollRunPdf: (id: number) => `/api/v1/hr/payroll/${id}/pdf`,
    attendance: '/api/v1/hr/attendance',
    attendanceImport: '/api/v1/hr/attendance/import-excel',
    attendancePolicy: '/api/v1/hr/attendance-policy',
    leaves: '/api/v1/hr/leaves',
    leaveTypes: '/api/v1/hr/leave-types',
    leaveRequests: '/api/v1/hr/leave-requests',
    leaveRequestApprove: (id: number) => `/api/v1/hr/leave-requests/${id}/approve`,
    leaveRequestReject: (id: number) => `/api/v1/hr/leave-requests/${id}/reject`,
    leaveBalanceMonthly: '/api/v1/hr/leave-balance-monthly',
    meLeaveBalanceMonthly: '/api/v1/hr/me/leave-balance-monthly',
    salaryAdvances: '/api/v1/hr/salary-advances',
    salaryAdvanceCancel: (id: number) => `/api/v1/hr/salary-advances/${id}/cancel`,
    advancePayments: '/api/v1/hr/advance-payments',
    penalties: '/api/v1/hr/penalties',
    penaltyTypes: '/api/v1/hr/penalty-types',
    leaderboard: '/api/v1/hr/leaderboard',
    departments: '/api/v1/hr/departments',
    shifts: '/api/v1/hr/shifts',
    rota: '/api/v1/hr/rota',
    rotaAssignments: '/api/v1/hr/rota/assignments',
    rotaTemplates: '/api/v1/hr/rota/templates',
    rotaTemplate: (id: number) => `/api/v1/hr/rota/templates/${id}`,
    rotaSwapRequests: '/api/v1/hr/rota/swap-requests',
    rotaSwapApprove: (id: number) => `/api/v1/hr/rota/swap-requests/${id}/approve`,
    configTaxBrackets: '/api/v1/hr/config/tax-brackets',
    configSocialInsurance: '/api/v1/hr/config/social-insurance',
  },
  inventory: {
    products: '/api/v1/inventory/products',
    product: (id: number) => `/api/v1/inventory/products/${id}`,
    movements: '/api/v1/inventory/movements',
    purchaseOrders: '/api/v1/inventory/purchase-orders',
    purchaseOrder: (id: number) => `/api/v1/inventory/purchase-orders/${id}`,
    purchaseRequests: '/api/v1/inventory/purchase-requests',
    purchaseRequest: (id: number) => `/api/v1/inventory/purchase-requests/${id}`,
    purchaseRequestApprove: (id: number) => `/api/v1/inventory/purchase-requests/${id}/approve`,
    purchaseRequestReject: (id: number) => `/api/v1/inventory/purchase-requests/${id}/reject`,
    purchaseRequestConvert: (id: number) => `/api/v1/inventory/purchase-requests/${id}/convert`,
    stockCounts: '/api/v1/inventory/stock-counts',
    stockCount: (id: number) => `/api/v1/inventory/stock-counts/${id}`,
    stockCountSubmit: (id: number) => `/api/v1/inventory/stock-counts/${id}/submit`,
    stockCountApprove: (id: number) => `/api/v1/inventory/stock-counts/${id}/approve`,
    lowStock: '/api/v1/inventory/low-stock',
    suppliers: '/api/v1/inventory/suppliers',
    categories: '/api/v1/inventory/categories',
    warehouses: '/api/v1/inventory/warehouses',
    barcodeLabels: '/api/v1/inventory/products/barcode-labels',
  },
  pms: {
    rooms: '/api/v1/pms/rooms',
    bookings: '/api/v1/pms/bookings',
    bookingCancel: (id: number) => `/api/v1/pms/bookings/${id}/cancel`,
    bookingCheckin: (id: number) => `/api/v1/pms/bookings/${id}/checkin`,
    bookingCheckout: (id: number) => `/api/v1/pms/bookings/${id}/checkout`,
    bookingEarlyLate: (id: number) => `/api/v1/pms/bookings/${id}/early-late`,
    housekeeping: '/api/v1/pms/housekeeping/tasks',
    nightAudit: '/api/v1/pms/night-audit',
    roomsAvailable: '/api/v1/pms/rooms/available',
  },
  crm: {
    leads: '/api/v1/crm/leads',
    lead: (id: number) => `/api/v1/crm/leads/${id}`,
    leadDetails: (id: number) => `/api/v1/crm/leads/${id}/details`,
    leadCallNotes: (id: number) => `/api/v1/crm/leads/${id}/call-notes`,
    leadConvert: (id: number) => `/api/v1/crm/leads/${id}/convert`,
    customers: '/api/v1/crm/customers',
    customer: (id: number) => `/api/v1/crm/customers/${id}`,
    customerInteractions: (id: number) => `/api/v1/crm/customers/${id}/interactions`,
    customerGroup: (id: number) => `/api/v1/crm/customers/${id}/group`,
    customerBlacklist: (id: number) => `/api/v1/crm/customers/${id}/blacklist`,
    customerGroups: '/api/v1/crm/customer-groups',
    opportunities: '/api/v1/crm/opportunities',
    opportunity: (id: number) => `/api/v1/crm/opportunities/${id}`,
    activities: '/api/v1/crm/activities',
    activity: (id: number) => `/api/v1/crm/activities/${id}`,
    campaigns: '/api/v1/crm/campaigns',
    campaign: (id: number) => `/api/v1/crm/campaigns/${id}`,
    guestProfiles: '/api/v1/crm/guest-profiles',
    leadSources: '/api/v1/crm/lead-sources',
    interactions: '/api/v1/crm/interactions',
    // Loyalty (C-01)
    loyaltyProgram: '/api/v1/crm/loyalty/program',
    loyaltyAccount: '/api/v1/crm/loyalty/account',
    loyaltyTransactions: '/api/v1/crm/loyalty/account/transactions',
    loyaltyRedeem: '/api/v1/crm/loyalty/redeem',
  },
  hub: {
    onlineBookings: '/api/v1/hub/online-bookings',
    onlineBookingConfirm: (id: number) => `/api/v1/hub/online-bookings/${id}/confirm`,
    onlineBookingCancel: (id: number) => `/api/v1/hub/online-bookings/${id}/cancel`,
    offers: '/api/v1/hub/offers',
    offer: (id: number) => `/api/v1/hub/offers/${id}`,
    pages: '/api/v1/hub/pages',
    page: (id: number) => `/api/v1/hub/pages/${id}`,
    blogPosts: '/api/v1/hub/blog/posts',
    blogPost: (id: number) => `/api/v1/hub/blog/posts/${id}`,
    contact: '/api/v1/hub/contact',
  },
  analytics: {
    // Note: there is no per-branch-id-in-path `/analytics/dashboard/{id}` route
    // on the backend (it's `GET /analytics/dashboard?branch_id=`, a 30-day
    // aggregate, not a "today" snapshot) — DashboardView.vue used to call a URL
    // shape that never matched any real route (always 404, silently swallowed).
    // `dailyStats` below is the real "today's numbers" endpoint and is what the
    // dashboard actually uses now.
    dailyStats: '/api/v1/analytics/daily-stats',
    // DailyStats is a nightly-computed snapshot (Celery beat, crontab hour=1,
    // always computes *yesterday*) — there is structurally no row for *today*
    // until 1am tomorrow. `revenue` computes restaurant/cafe/pms/beach totals
    // live from the source tables for any date range, so the dashboard falls
    // back to it for same-day figures instead of always showing 0.
    revenue: '/api/v1/analytics/revenue',
    // Full dashboard aggregate (revenue_30d + hr + maintenance + crm + inventory + reviews)
    dashboard: '/api/v1/analytics/dashboard',
    // Occupancy by month — ?branch_id=&month=&year=
    occupancy: '/api/v1/analytics/occupancy',
    // HR summary (active employees + last payroll) — ?branch_id=
    hr: '/api/v1/analytics/hr',
    // Maintenance KPIs (open/critical work orders) — ?branch_id=
    maintenance: '/api/v1/analytics/maintenance',
    // CRM pipeline (customers + opportunities by stage) — ?branch_id=
    crm: '/api/v1/analytics/crm',
    // Inventory alerts (low-stock + out-of-stock counts) — ?branch_id=
    inventory: '/api/v1/analytics/inventory',
    // Utility readings (energy/water/gas) — GET list, POST create
    utilities: '/api/v1/analytics/utilities',
    // Energy KPIs (cost per kWh/guest) — ?branch_id=&period=YYYY-MM
    energy: '/api/v1/analytics/energy',
    energyTrend: '/api/v1/analytics/energy/trend',
    energyTrendExport: '/api/v1/analytics/energy/trend/export',
    // Guest reviews list — ?branch_id= (published only, unless booking_id/timeshare_visit_id provided)
    reviews: '/api/v1/analytics/reviews',
    // Per-category review insights (GSS score breakdown) — ?branch_id=
    reviewInsights: '/api/v1/analytics/reviews/insights',
    // Submit a guest review via survey JWT token — ?token=
    reviewSubmit: '/api/v1/analytics/reviews/submit',
    // Generate survey token for a PMS booking — GET /analytics/reviews/survey-token/{booking_id}
    reviewSurveyToken: (bookingId: number) => `/api/v1/analytics/reviews/survey-token/${bookingId}`,
    // Generate survey token for a timeshare visit
    reviewTimeshareSurveyToken: (visitId: number) => `/api/v1/analytics/reviews/survey-token/timeshare/${visitId}`,
    // Queue WhatsApp survey delivery for a timeshare visit
    reviewTimeshareSurveySend: (visitId: number) => `/api/v1/analytics/reviews/survey-token/timeshare/${visitId}/send`,
  },
  timeshare: {
    contracts: '/api/v1/timeshare/contracts',
    contract: (id: number) => `/api/v1/timeshare/contracts/${id}`,
    contractCancel: (id: number) => `/api/v1/timeshare/contracts/${id}/cancel`,
    contractPdf: (id: number) => `/api/v1/timeshare/contracts/${id}/pdf`,
    contractTransferUnit: (id: number) => `/api/v1/timeshare/contracts/${id}/transfer-unit`,
    contractsImport: '/api/v1/timeshare/contracts/import-excel',
    installments: '/api/v1/timeshare/installments',
    installmentPay: (id: number) => `/api/v1/timeshare/installments/${id}/pay`,
    installmentsMonthlyReport: '/api/v1/timeshare/installments/monthly-report',
    visits: '/api/v1/timeshare/visits',
    visit: (id: number) => `/api/v1/timeshare/visits/${id}`,
    upcomingVisits: '/api/v1/timeshare/upcoming-visits',
    units: '/api/v1/timeshare/units',
    availableWeeks: '/api/v1/timeshare/available-weeks',
    waitlist: '/api/v1/timeshare/waitlist',
    stats: '/api/v1/timeshare/stats',
    salesDashboard: '/api/v1/timeshare/sales-dashboard',
    salesDashboardExport: '/api/v1/timeshare/sales-dashboard/export',
    csSummary: '/api/v1/timeshare/cs-summary',
    calendar: '/api/v1/timeshare/calendar',
  },
  maintenance: {
    assets: '/api/v1/maintenance/assets',
    asset: (id: number) => `/api/v1/maintenance/assets/${id}`,
    assetDispose: (id: number) => `/api/v1/maintenance/assets/${id}/dispose`,
    workOrders: '/api/v1/maintenance/work-orders',
    workOrder: (id: number) => `/api/v1/maintenance/work-orders/${id}`,
    workOrderComplete: (id: number) => `/api/v1/maintenance/work-orders/${id}/complete`,
    workOrderParts: (id: number) => `/api/v1/maintenance/work-orders/${id}/parts`,
    preventiveSchedules: '/api/v1/maintenance/preventive-schedules',
    preventiveSchedule: (id: number) => `/api/v1/maintenance/preventive-schedules/${id}`,
  },
  leasing: {
    contracts: '/api/v1/leasing/contracts',
    contract: (id: number) => `/api/v1/leasing/contracts/${id}`,
    contractCashLogs: (id: number) => `/api/v1/leasing/contracts/${id}/cash-logs`,
    contractApplyPenalties: (id: number) => `/api/v1/leasing/contracts/${id}/apply-penalties`,
    payments: '/api/v1/leasing/payments',
    payment: (id: number) => `/api/v1/leasing/payments/${id}`,
    paymentPay: (id: number) => `/api/v1/leasing/payments/${id}/pay`,
    paymentReceipt: (id: number) => `/api/v1/leasing/payments/${id}/receipt`,
    cashLogs: '/api/v1/leasing/cash-logs',
  },
  pms_extra: {
    roomTypes:        '/api/v1/pms/room-types',
    ratePlans:        '/api/v1/pms/rate-plans',
    nightAuditRun:    '/api/v1/pms/night-audit/run',
    housekeepingTask: (id: number) => `/api/v1/pms/housekeeping/tasks/${id}`,
  },
  hr_extra: {
    meProfile:         '/api/v1/hr/me/profile',
    meAttendance:      '/api/v1/hr/me/attendance',
    meAttendancePunchIn:  '/api/v1/hr/me/attendance/punch-in',
    meAttendancePunchOut: '/api/v1/hr/me/attendance/punch-out',
    meLeaves:          '/api/v1/hr/me/leaves',
    meLeaveRequest:    '/api/v1/hr/me/leaves/request',
    meLeaveBalance:    '/api/v1/hr/me/leave-balance-monthly',
    mePayslips:        '/api/v1/hr/me/payslips',
    configTaxBrackets:     '/api/v1/hr/config/tax-brackets',
    configSocialInsurance: '/api/v1/hr/config/social-insurance',
  },
  settings: {
    get: '/api/v1/settings',
    set: (key: string) => `/api/v1/settings/${encodeURIComponent(key)}`,
  },
  permissions: {
    list:       '/api/v1/permissions',
    permission: (id: number) => `/api/v1/permissions/${id}`,
    catalog:    '/api/v1/permissions/catalog',
    me:         '/api/v1/permissions/me',
    users:      '/api/v1/users',
    user:       (id: number) => `/api/v1/users/${id}`,
    createUser: '/api/v1/users',
  },
  finance_eta: {
    invoices: '/api/v1/finance/eta/invoices',
  },
}
