/**
 * The Design System's single icon set — every icon anywhere in either app
 * (once screens migrate onto <AppIcon>, a later stage) must come from this
 * curated map, never a one-off inline <svg> or emoji. Backed by
 * @heroicons/vue (MIT, tree-shakeable, Vue 3 native) so we don't maintain
 * hand-rolled SVG paths — but consumers only ever see the semantic
 * `IconName` below, never the heroicons import path, so the underlying
 * library could be swapped later without touching a single call site.
 *
 * Curated deliberately (not "export everything heroicons ships") — an
 * unbounded icon set is how projects end up with 5 different icons that all
 * mean "delete". Add a new entry here only when an existing one truly
 * doesn't fit; check this list before reaching for a raw <svg> anywhere.
 */
import {
  CheckIcon, XMarkIcon, PlusIcon, MinusIcon, TrashIcon, PencilIcon,
  MagnifyingGlassIcon, FunnelIcon, AdjustmentsHorizontalIcon,
  ChevronDownIcon, ChevronUpIcon, ChevronLeftIcon, ChevronRightIcon,
  ArrowLeftIcon, ArrowRightIcon, ArrowPathIcon, ArrowDownTrayIcon, ArrowUpTrayIcon,
  ArrowTopRightOnSquareIcon,
  Bars3Icon, EllipsisHorizontalIcon, EllipsisVerticalIcon,
  BellIcon, UserIcon, UsersIcon, UserCircleIcon, IdentificationIcon,
  HomeIcon, BuildingStorefrontIcon, BuildingOffice2Icon,
  CalendarDaysIcon, ClockIcon, CurrencyDollarIcon, BanknotesIcon, CreditCardIcon,
  ReceiptPercentIcon, ShoppingCartIcon, TagIcon, ClipboardDocumentListIcon,
  ClipboardDocumentCheckIcon, DocumentTextIcon, DocumentDuplicateIcon,
  Cog6ToothIcon, LockClosedIcon, LockOpenIcon, KeyIcon, ShieldCheckIcon, ShieldExclamationIcon,
  EyeIcon, EyeSlashIcon, StarIcon, HeartIcon, MapPinIcon, PhoneIcon, EnvelopeIcon,
  ChatBubbleLeftRightIcon, InformationCircleIcon, ExclamationTriangleIcon,
  ExclamationCircleIcon, CheckCircleIcon, XCircleIcon, QuestionMarkCircleIcon,
  WrenchScrewdriverIcon, TruckIcon, QrCodeIcon, CameraIcon, PhotoIcon,
  PaperAirplaneIcon, LinkIcon, GlobeAltIcon, MoonIcon, SunIcon,
  BriefcaseIcon, AcademicCapIcon, FireIcon, CakeIcon, SparklesIcon,
  TableCellsIcon, Squares2X2Icon, ListBulletIcon, PrinterIcon,
  ArrowLeftOnRectangleIcon, ArrowRightOnRectangleIcon, PlusCircleIcon,
  MinusCircleIcon, NoSymbolIcon, CheckBadgeIcon, FlagIcon, BuildingOfficeIcon,
  ChartBarIcon, ChartPieIcon, PresentationChartLineIcon, InboxIcon,
  ArchiveBoxIcon, CubeIcon, ScaleIcon, CalculatorIcon, DevicePhoneMobileIcon,
  ComputerDesktopIcon, WifiIcon, SignalSlashIcon,
} from '@heroicons/vue/24/outline'

export const ICONS = {
  check: CheckIcon,
  close: XMarkIcon,
  add: PlusIcon,
  remove: MinusIcon,
  delete: TrashIcon,
  edit: PencilIcon,
  search: MagnifyingGlassIcon,
  filter: FunnelIcon,
  adjustments: AdjustmentsHorizontalIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-up': ChevronUpIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  refresh: ArrowPathIcon,
  download: ArrowDownTrayIcon,
  upload: ArrowUpTrayIcon,
  'external-link': ArrowTopRightOnSquareIcon,
  menu: Bars3Icon,
  'more-horizontal': EllipsisHorizontalIcon,
  'more-vertical': EllipsisVerticalIcon,
  bell: BellIcon,
  user: UserIcon,
  users: UsersIcon,
  'user-circle': UserCircleIcon,
  id: IdentificationIcon,
  home: HomeIcon,
  outlet: BuildingStorefrontIcon,
  branch: BuildingOffice2Icon,
  building: BuildingOfficeIcon,
  calendar: CalendarDaysIcon,
  clock: ClockIcon,
  currency: CurrencyDollarIcon,
  cash: BanknotesIcon,
  card: CreditCardIcon,
  discount: ReceiptPercentIcon,
  cart: ShoppingCartIcon,
  tag: TagIcon,
  clipboard: ClipboardDocumentListIcon,
  'clipboard-check': ClipboardDocumentCheckIcon,
  document: DocumentTextIcon,
  'document-duplicate': DocumentDuplicateIcon,
  settings: Cog6ToothIcon,
  lock: LockClosedIcon,
  unlock: LockOpenIcon,
  key: KeyIcon,
  shield: ShieldCheckIcon,
  'shield-warning': ShieldExclamationIcon,
  'eye': EyeIcon,
  'eye-off': EyeSlashIcon,
  star: StarIcon,
  heart: HeartIcon,
  location: MapPinIcon,
  phone: PhoneIcon,
  email: EnvelopeIcon,
  chat: ChatBubbleLeftRightIcon,
  info: InformationCircleIcon,
  warning: ExclamationTriangleIcon,
  'alert-circle': ExclamationCircleIcon,
  success: CheckCircleIcon,
  error: XCircleIcon,
  help: QuestionMarkCircleIcon,
  maintenance: WrenchScrewdriverIcon,
  delivery: TruckIcon,
  qrcode: QrCodeIcon,
  camera: CameraIcon,
  photo: PhotoIcon,
  send: PaperAirplaneIcon,
  link: LinkIcon,
  language: GlobeAltIcon,
  moon: MoonIcon,
  sun: SunIcon,
  hr: BriefcaseIcon,
  training: AcademicCapIcon,
  kitchen: FireIcon,
  dessert: CakeIcon,
  sparkles: SparklesIcon,
  table: TableCellsIcon,
  grid: Squares2X2Icon,
  list: ListBulletIcon,
  print: PrinterIcon,
  login: ArrowLeftOnRectangleIcon,
  logout: ArrowRightOnRectangleIcon,
  'add-circle': PlusCircleIcon,
  'remove-circle': MinusCircleIcon,
  void: NoSymbolIcon,
  verified: CheckBadgeIcon,
  flag: FlagIcon,
  chart: ChartBarIcon,
  'chart-pie': ChartPieIcon,
  trend: PresentationChartLineIcon,
  inbox: InboxIcon,
  archive: ArchiveBoxIcon,
  inventory: CubeIcon,
  scale: ScaleIcon,
  calculator: CalculatorIcon,
  mobile: DevicePhoneMobileIcon,
  desktop: ComputerDesktopIcon,
  online: WifiIcon,
  offline: SignalSlashIcon,
} as const

export type IconName = keyof typeof ICONS
