"""dining_unified_module_initial_schema

Revision ID: 0bd6f63e5446
Revises: b3c7d9e1f2a4
Create Date: 2026-07-12 16:50:07.747356

wagdy.md D-02 (Dining Module Merge, Batch A) — creates the new `dining_*`
tables (app/modules/dining/models.py, a superset of restaurant.models +
cafe.models) and then COPIES (not moves) every existing restaurant/cafe
menu/table/order row into them.

🔴 real-money-data risk — this migration was built and fully verified
against a disposable devtest database seeded with representative
restaurant + cafe data (variants, recipe lines, extras, held orders, a
refunded order) BEFORE being run anywhere near real data, and a real
pg_dump backup was taken and restore-verified (exact COUNT(*) match
across branches/users/orders/cafe_orders/menu_items/cafe_items) right
before this file was authored. See DINING_CUTOVER_PLAN.md at the repo
root for the full verification log and for why `restaurant`/`cafe`
remain the live source of truth after this migration runs (they are —
this migration only adds rows to new tables, it does not touch a single
existing row in `orders`/`cafe_orders`/`menu_items`/`cafe_items`/etc).

Why every copied entity gets `legacy_module` + `legacy_id` (unique)
instead of reusing the original primary key: `restaurant.Order.id` and
`cafe.CafeOrder.id` are independent sequences that legitimately collide
(both start at 1) — merging them into one `dining_orders.id` sequence is
not possible without literal PK reuse breaking on the very first
collision. `legacy_module`/`legacy_id` preserves full traceability back
to the original row without that impossibility, and the SQL below
correlates parent → child rows (e.g. an order's items, a variant's
recipe lines) purely through it — no Python-side ID maps, no per-row
loop, just INSERT...SELECT with correlated subqueries. This also makes
the copy idempotent/safe to re-run: every copy statement filters out
rows whose (legacy_module, legacy_id) already exists in the target
table, so a partial failure and retry does not create duplicates.

Outlets: one `restaurant` + one `cafe` Outlet row is created per branch
in `branches` (every branch always has both modules available — CLAUDE.md
§12, no per-module toggle in this project), with
`revenue_account_code` seeded to the exact `4200`/`4400` literals the
old services.py had hardcoded, so nothing about real financial reporting
changes yet (D-05, out of scope here, is the actual analytics/finance
read-cutover — see DINING_CUTOVER_PLAN.md).
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bd6f63e5446'
down_revision: Union[str, None] = 'b3c7d9e1f2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ─────────────────────── Schema (new tables) ───────────────────────
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dining_outlets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('outlet_type', sa.String(length=30), nullable=False),
    sa.Column('revenue_account_code', sa.String(length=10), nullable=False),
    sa.Column('default_service_charge_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_module', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'name', name='uq_dining_outlet_branch_name')
    )
    op.create_index('ix_dining_outlets_branch_id', 'dining_outlets', ['branch_id'], unique=False)
    op.create_table('dining_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_module', sa.String(length=20), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['dining_outlets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_module', 'legacy_id', name='uq_dining_category_legacy')
    )
    op.create_index('ix_dining_categories_outlet_id', 'dining_categories', ['outlet_id'], unique=False)
    op.create_table('dining_kds_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stations', sa.JSON(), nullable=False),
    sa.Column('display_mode', sa.String(length=20), nullable=False),
    sa.Column('alert_after_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['dining_outlets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dining_venue_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('occupied_at', sa.DateTime(), nullable=True),
    sa.Column('grid_row', sa.Integer(), nullable=True),
    sa.Column('grid_col', sa.Integer(), nullable=True),
    sa.Column('legacy_module', sa.String(length=20), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['dining_outlets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_module', 'legacy_id', name='uq_dining_table_legacy')
    )
    op.create_index('ix_dining_venue_tables_outlet_id', 'dining_venue_tables', ['outlet_id'], unique=False)
    op.create_table('dining_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('preparation_minutes', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('station', sa.String(length=50), nullable=False),
    sa.Column('linked_product_id', sa.Integer(), nullable=True),
    sa.Column('legacy_module', sa.String(length=20), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['dining_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['dining_outlets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_module', 'legacy_id', name='uq_dining_item_legacy')
    )
    op.create_index('ix_dining_items_outlet_id', 'dining_items', ['outlet_id'], unique=False)
    op.create_index('ix_dining_items_category_id', 'dining_items', ['category_id'], unique=False)
    op.create_table('dining_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('guests_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('waiter_id', sa.Integer(), nullable=True),
    sa.Column('folio_id', sa.Integer(), nullable=True),
    sa.Column('applied_discount_rule_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('client_local_id', sa.String(length=60), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('legacy_module', sa.String(length=20), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['dining_outlets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['dining_venue_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_local_id'),
    sa.UniqueConstraint('legacy_module', 'legacy_id', name='uq_dining_order_legacy'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index('ix_dining_orders_branch_id', 'dining_orders', ['branch_id'], unique=False)
    op.create_index('ix_dining_orders_outlet_id', 'dining_orders', ['outlet_id'], unique=False)
    op.create_index('ix_dining_orders_status', 'dining_orders', ['status'], unique=False)
    op.create_table('dining_item_extra_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('min_select', sa.Integer(), nullable=False),
    sa.Column('max_select', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('legacy_module', sa.String(length=20), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['dining_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_module', 'legacy_id', name='uq_dining_item_extra_group_legacy')
    )
    op.create_index('ix_dining_item_extra_groups_item_id', 'dining_item_extra_groups', ['item_id'], unique=False)
    op.create_table('dining_item_recipe_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['dining_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'product_id', name='uq_dining_item_recipe_product')
    )
    op.create_table('dining_item_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('legacy_module', sa.String(length=20), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['dining_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'name', name='uq_dining_item_variant_name'),
    sa.UniqueConstraint('legacy_module', 'legacy_id', name='uq_dining_item_variant_legacy')
    )
    op.create_index('ix_dining_item_variants_item_id', 'dining_item_variants', ['item_id'], unique=False)
    op.create_table('dining_kitchen_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=50), nullable=False),
    sa.Column('items_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['dining_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['dining_outlets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dining_kitchen_tickets_branch_status', 'dining_kitchen_tickets', ['branch_id', 'status'], unique=False)
    op.create_table('dining_item_extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('price_addition', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['dining_item_extra_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dining_item_variant_recipe_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['dining_item_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'product_id', name='uq_dining_item_variant_recipe_product')
    )
    op.create_table('dining_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voided_reason', sa.String(length=200), nullable=True),
    sa.Column('voided_by', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('legacy_module', sa.String(length=20), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['dining_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['dining_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['dining_item_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_module', 'legacy_id', name='uq_dining_order_item_legacy')
    )
    op.create_index('ix_dining_order_items_order_id', 'dining_order_items', ['order_id'], unique=False)
    op.create_index('ix_dining_order_items_item_id', 'dining_order_items', ['item_id'], unique=False)
    op.create_table('dining_order_item_extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('extra_id', sa.Integer(), nullable=True),
    sa.Column('extra_name', sa.String(length=100), nullable=False),
    sa.Column('price_addition', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extra_id'], ['dining_item_extras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['dining_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # (Autogenerate also detected two unrelated pre-existing index-drift
    # entries on advance_payments/salary_advances — left untouched here,
    # out of scope for a dining-only migration; not caused by this change.)

    # ─────────────────────── Data copy (restaurant + cafe → dining) ────
    _copy_restaurant_and_cafe_data_into_dining(op.get_bind())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dining_order_item_extras')
    op.drop_table('dining_order_items')
    op.drop_table('dining_item_variant_recipe_lines')
    op.drop_table('dining_item_extras')
    op.drop_table('dining_kitchen_tickets')
    op.drop_table('dining_item_variants')
    op.drop_table('dining_item_recipe_lines')
    op.drop_table('dining_item_extra_groups')
    op.drop_table('dining_orders')
    op.drop_table('dining_items')
    op.drop_table('dining_venue_tables')
    op.drop_table('dining_kds_screens')
    op.drop_table('dining_categories')
    op.drop_table('dining_outlets')
    # ### end Alembic commands ###
    # No separate data-uncopy step needed — dropping the tables above
    # removes every copied row with them. restaurant/cafe's own tables
    # were never touched by upgrade(), so downgrade leaves them exactly
    # as they were too.


def _copy_restaurant_and_cafe_data_into_dining(bind) -> None:
    """SQL-only copy, no ORM/Python loops — every statement is an
    INSERT...SELECT that correlates to its new parent via
    (legacy_module, legacy_id) or, where the natural key is already
    unique in both schemas (recipe lines keyed by (item_id, product_id)),
    directly through it. ``WHERE NOT EXISTS`` on every insert makes this
    idempotent: re-running the migration (e.g. after a partial failure)
    never creates duplicate copies.

    Order matters — each block depends on the previous one's rows
    already existing (outlets before categories before items before
    orders before order_items before order_item_extras)."""

    # ── Outlets: one restaurant + one cafe per branch (CLAUDE.md §12 —
    # every branch always has both modules, no per-module toggle) ──────
    bind.execute(sa.text("""
        INSERT INTO dining_outlets (branch_id, name, name_ar, outlet_type, revenue_account_code, is_active, legacy_module, created_at, updated_at)
        SELECT b.id, 'المطعم', 'المطعم', 'restaurant', '4200', true, 'restaurant', now(), now()
        FROM branches b
        WHERE NOT EXISTS (SELECT 1 FROM dining_outlets o WHERE o.branch_id = b.id AND o.legacy_module = 'restaurant')
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_outlets (branch_id, name, name_ar, outlet_type, revenue_account_code, is_active, legacy_module, created_at, updated_at)
        SELECT b.id, 'الكافيه', 'الكافيه', 'cafe', '4400', true, 'cafe', now(), now()
        FROM branches b
        WHERE NOT EXISTS (SELECT 1 FROM dining_outlets o WHERE o.branch_id = b.id AND o.legacy_module = 'cafe')
    """))

    # ── Categories ───────────────────────────────────────────────────
    bind.execute(sa.text("""
        INSERT INTO dining_categories (branch_id, outlet_id, name, name_ar, sort_order, is_active, legacy_module, legacy_id, created_at, updated_at)
        SELECT mc.branch_id,
               (SELECT o.id FROM dining_outlets o WHERE o.branch_id = mc.branch_id AND o.legacy_module = 'restaurant'),
               mc.name, mc.name_ar, mc.sort_order, mc.is_active, 'restaurant', mc.id, mc.created_at, mc.updated_at
        FROM menu_categories mc
        WHERE NOT EXISTS (SELECT 1 FROM dining_categories dc WHERE dc.legacy_module = 'restaurant' AND dc.legacy_id = mc.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_categories (branch_id, outlet_id, name, name_ar, sort_order, is_active, legacy_module, legacy_id, created_at, updated_at)
        SELECT cc.branch_id,
               (SELECT o.id FROM dining_outlets o WHERE o.branch_id = cc.branch_id AND o.legacy_module = 'cafe'),
               cc.name, cc.name_ar, cc.sort_order, cc.is_active, 'cafe', cc.id, cc.created_at, cc.updated_at
        FROM cafe_categories cc
        WHERE NOT EXISTS (SELECT 1 FROM dining_categories dc WHERE dc.legacy_module = 'cafe' AND dc.legacy_id = cc.id)
    """))

    # ── Items ────────────────────────────────────────────────────────
    bind.execute(sa.text("""
        INSERT INTO dining_items (branch_id, outlet_id, category_id, name, name_ar, price, cost, is_available,
                                   preparation_minutes, image_url, station, linked_product_id, legacy_module, legacy_id, created_at, updated_at)
        SELECT mi.branch_id,
               (SELECT o.id FROM dining_outlets o WHERE o.branch_id = mi.branch_id AND o.legacy_module = 'restaurant'),
               (SELECT dc.id FROM dining_categories dc WHERE dc.legacy_module = 'restaurant' AND dc.legacy_id = mi.category_id),
               mi.name, mi.name_ar, mi.price, mi.cost, mi.is_available, mi.preparation_minutes, mi.image_url,
               mi.station, mi.linked_product_id, 'restaurant', mi.id, mi.created_at, mi.updated_at
        FROM menu_items mi
        WHERE NOT EXISTS (SELECT 1 FROM dining_items di WHERE di.legacy_module = 'restaurant' AND di.legacy_id = mi.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_items (branch_id, outlet_id, category_id, name, name_ar, price, cost, is_available,
                                   preparation_minutes, image_url, station, linked_product_id, legacy_module, legacy_id, created_at, updated_at)
        SELECT ci.branch_id,
               (SELECT o.id FROM dining_outlets o WHERE o.branch_id = ci.branch_id AND o.legacy_module = 'cafe'),
               (SELECT dc.id FROM dining_categories dc WHERE dc.legacy_module = 'cafe' AND dc.legacy_id = ci.category_id),
               ci.name, ci.name_ar, ci.price, ci.cost, ci.is_available, ci.preparation_minutes, ci.image_url,
               ci.station, ci.linked_product_id, 'cafe', ci.id, ci.created_at, ci.updated_at
        FROM cafe_items ci
        WHERE NOT EXISTS (SELECT 1 FROM dining_items di WHERE di.legacy_module = 'cafe' AND di.legacy_id = ci.id)
    """))

    # ── Extra groups + extras ───────────────────────────────────────
    bind.execute(sa.text("""
        INSERT INTO dining_item_extra_groups (item_id, name, name_ar, min_select, max_select, sort_order, legacy_module, legacy_id, created_at, updated_at)
        SELECT (SELECT di.id FROM dining_items di WHERE di.legacy_module = 'restaurant' AND di.legacy_id = g.menu_item_id),
               g.name, g.name_ar, g.min_select, g.max_select, g.sort_order, 'restaurant', g.id, g.created_at, g.updated_at
        FROM menu_item_extra_groups g
        WHERE NOT EXISTS (SELECT 1 FROM dining_item_extra_groups deg WHERE deg.legacy_module = 'restaurant' AND deg.legacy_id = g.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_item_extra_groups (item_id, name, name_ar, min_select, max_select, sort_order, legacy_module, legacy_id, created_at, updated_at)
        SELECT (SELECT di.id FROM dining_items di WHERE di.legacy_module = 'cafe' AND di.legacy_id = g.cafe_item_id),
               g.name, g.name_ar, g.min_select, g.max_select, g.sort_order, 'cafe', g.id, g.created_at, g.updated_at
        FROM cafe_menu_item_extra_groups g
        WHERE NOT EXISTS (SELECT 1 FROM dining_item_extra_groups deg WHERE deg.legacy_module = 'cafe' AND deg.legacy_id = g.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_item_extras (group_id, name, name_ar, price_addition, is_available, sort_order, created_at, updated_at)
        SELECT (SELECT deg.id FROM dining_item_extra_groups deg WHERE deg.legacy_module = 'restaurant' AND deg.legacy_id = e.group_id),
               e.name, e.name_ar, e.price_addition, e.is_available, e.sort_order, e.created_at, e.updated_at
        FROM menu_item_extras e
        WHERE NOT EXISTS (
            SELECT 1 FROM dining_item_extras de
            JOIN dining_item_extra_groups deg ON deg.id = de.group_id
            WHERE deg.legacy_module = 'restaurant' AND deg.legacy_id = e.group_id AND de.name = e.name
        )
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_item_extras (group_id, name, name_ar, price_addition, is_available, sort_order, created_at, updated_at)
        SELECT (SELECT deg.id FROM dining_item_extra_groups deg WHERE deg.legacy_module = 'cafe' AND deg.legacy_id = e.group_id),
               e.name, e.name_ar, e.price_addition, e.is_available, e.sort_order, e.created_at, e.updated_at
        FROM cafe_menu_item_extras e
        WHERE NOT EXISTS (
            SELECT 1 FROM dining_item_extras de
            JOIN dining_item_extra_groups deg ON deg.id = de.group_id
            WHERE deg.legacy_module = 'cafe' AND deg.legacy_id = e.group_id AND de.name = e.name
        )
    """))

    # ── Recipe lines (natural key (item_id, product_id) already unique
    # in both schemas — correlate directly through it) ─────────────────
    bind.execute(sa.text("""
        INSERT INTO dining_item_recipe_lines (item_id, product_id, quantity_per_unit, notes, created_at, updated_at)
        SELECT (SELECT di.id FROM dining_items di WHERE di.legacy_module = 'restaurant' AND di.legacy_id = rl.menu_item_id),
               rl.product_id, rl.quantity_per_unit, rl.notes, rl.created_at, rl.updated_at
        FROM menu_item_recipe_lines rl
        WHERE NOT EXISTS (
            SELECT 1 FROM dining_item_recipe_lines drl
            JOIN dining_items di ON di.id = drl.item_id
            WHERE di.legacy_module = 'restaurant' AND di.legacy_id = rl.menu_item_id AND drl.product_id = rl.product_id
        )
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_item_recipe_lines (item_id, product_id, quantity_per_unit, notes, created_at, updated_at)
        SELECT (SELECT di.id FROM dining_items di WHERE di.legacy_module = 'cafe' AND di.legacy_id = rl.cafe_item_id),
               rl.product_id, rl.quantity_per_unit, rl.notes, rl.created_at, rl.updated_at
        FROM cafe_item_recipe_lines rl
        WHERE NOT EXISTS (
            SELECT 1 FROM dining_item_recipe_lines drl
            JOIN dining_items di ON di.id = drl.item_id
            WHERE di.legacy_module = 'cafe' AND di.legacy_id = rl.cafe_item_id AND drl.product_id = rl.product_id
        )
    """))

    # ── Variants + their own recipe lines ───────────────────────────
    bind.execute(sa.text("""
        INSERT INTO dining_item_variants (item_id, name, name_ar, price, is_available, sort_order, legacy_module, legacy_id, created_at, updated_at)
        SELECT (SELECT di.id FROM dining_items di WHERE di.legacy_module = 'restaurant' AND di.legacy_id = v.menu_item_id),
               v.name, v.name_ar, v.price, v.is_available, v.sort_order, 'restaurant', v.id, v.created_at, v.updated_at
        FROM menu_item_variants v
        WHERE NOT EXISTS (SELECT 1 FROM dining_item_variants dv WHERE dv.legacy_module = 'restaurant' AND dv.legacy_id = v.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_item_variants (item_id, name, name_ar, price, is_available, sort_order, legacy_module, legacy_id, created_at, updated_at)
        SELECT (SELECT di.id FROM dining_items di WHERE di.legacy_module = 'cafe' AND di.legacy_id = v.cafe_item_id),
               v.name, v.name_ar, v.price, v.is_available, v.sort_order, 'cafe', v.id, v.created_at, v.updated_at
        FROM cafe_item_variants v
        WHERE NOT EXISTS (SELECT 1 FROM dining_item_variants dv WHERE dv.legacy_module = 'cafe' AND dv.legacy_id = v.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_item_variant_recipe_lines (variant_id, product_id, quantity_per_unit, notes, created_at, updated_at)
        SELECT (SELECT dv.id FROM dining_item_variants dv WHERE dv.legacy_module = 'restaurant' AND dv.legacy_id = vrl.variant_id),
               vrl.product_id, vrl.quantity_per_unit, vrl.notes, vrl.created_at, vrl.updated_at
        FROM menu_item_variant_recipe_lines vrl
        WHERE NOT EXISTS (
            SELECT 1 FROM dining_item_variant_recipe_lines dvrl
            JOIN dining_item_variants dv ON dv.id = dvrl.variant_id
            WHERE dv.legacy_module = 'restaurant' AND dv.legacy_id = vrl.variant_id AND dvrl.product_id = vrl.product_id
        )
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_item_variant_recipe_lines (variant_id, product_id, quantity_per_unit, notes, created_at, updated_at)
        SELECT (SELECT dv.id FROM dining_item_variants dv WHERE dv.legacy_module = 'cafe' AND dv.legacy_id = vrl.variant_id),
               vrl.product_id, vrl.quantity_per_unit, vrl.notes, vrl.created_at, vrl.updated_at
        FROM cafe_item_variant_recipe_lines vrl
        WHERE NOT EXISTS (
            SELECT 1 FROM dining_item_variant_recipe_lines dvrl
            JOIN dining_item_variants dv ON dv.id = dvrl.variant_id
            WHERE dv.legacy_module = 'cafe' AND dv.legacy_id = vrl.variant_id AND dvrl.product_id = vrl.product_id
        )
    """))

    # ── Tables ───────────────────────────────────────────────────────
    bind.execute(sa.text("""
        INSERT INTO dining_venue_tables (branch_id, outlet_id, table_number, capacity, status, section, occupied_at,
                                          grid_row, grid_col, legacy_module, legacy_id, created_at, updated_at)
        SELECT t.branch_id,
               (SELECT o.id FROM dining_outlets o WHERE o.branch_id = t.branch_id AND o.legacy_module = 'restaurant'),
               t.table_number, t.capacity, t.status, t.section, t.occupied_at, t.grid_row, t.grid_col,
               'restaurant', t.id, t.created_at, t.updated_at
        FROM dining_tables t
        WHERE NOT EXISTS (SELECT 1 FROM dining_venue_tables vt WHERE vt.legacy_module = 'restaurant' AND vt.legacy_id = t.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_venue_tables (branch_id, outlet_id, table_number, capacity, status, section, occupied_at,
                                          grid_row, grid_col, legacy_module, legacy_id, created_at, updated_at)
        SELECT t.branch_id,
               (SELECT o.id FROM dining_outlets o WHERE o.branch_id = t.branch_id AND o.legacy_module = 'cafe'),
               t.table_number, t.capacity, t.status, t.section, t.occupied_at, NULL, NULL,
               'cafe', t.id, t.created_at, t.updated_at
        FROM cafe_tables t
        WHERE NOT EXISTS (SELECT 1 FROM dining_venue_tables vt WHERE vt.legacy_module = 'cafe' AND vt.legacy_id = t.id)
    """))

    # ── Orders ───────────────────────────────────────────────────────
    bind.execute(sa.text("""
        INSERT INTO dining_orders (branch_id, outlet_id, table_id, order_number, status, order_type, subtotal, vat_amount,
                                    service_charge, discount_amount, total, refunded_amount, guests_count, notes, waiter_id,
                                    folio_id, applied_discount_rule_id, customer_id, client_local_id, payment_method,
                                    legacy_module, legacy_id, created_at, updated_at)
        SELECT o.branch_id,
               (SELECT out.id FROM dining_outlets out WHERE out.branch_id = o.branch_id AND out.legacy_module = 'restaurant'),
               (SELECT vt.id FROM dining_venue_tables vt WHERE vt.legacy_module = 'restaurant' AND vt.legacy_id = o.table_id),
               o.order_number, o.status, o.order_type, o.subtotal, o.vat_amount, o.service_charge, o.discount_amount,
               o.total, o.refunded_amount, o.guests_count, o.notes, o.waiter_id, o.folio_id, o.applied_discount_rule_id,
               o.customer_id, NULL, o.payment_method, 'restaurant', o.id, o.created_at, o.updated_at
        FROM orders o
        WHERE NOT EXISTS (SELECT 1 FROM dining_orders do2 WHERE do2.legacy_module = 'restaurant' AND do2.legacy_id = o.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_orders (branch_id, outlet_id, table_id, order_number, status, order_type, subtotal, vat_amount,
                                    service_charge, discount_amount, total, refunded_amount, guests_count, notes, waiter_id,
                                    folio_id, applied_discount_rule_id, customer_id, client_local_id, payment_method,
                                    legacy_module, legacy_id, created_at, updated_at)
        SELECT co.branch_id,
               (SELECT out.id FROM dining_outlets out WHERE out.branch_id = co.branch_id AND out.legacy_module = 'cafe'),
               (SELECT vt.id FROM dining_venue_tables vt WHERE vt.legacy_module = 'cafe' AND vt.legacy_id = co.table_id),
               co.order_number, co.status, co.order_type, co.subtotal, co.vat_amount, co.service_charge, co.discount_amount,
               co.total, co.refunded_amount, 1, co.notes, co.waiter_id, co.folio_id, co.applied_discount_rule_id,
               co.customer_id, NULL, co.payment_method, 'cafe', co.id, co.created_at, co.updated_at
        FROM cafe_orders co
        WHERE NOT EXISTS (SELECT 1 FROM dining_orders do2 WHERE do2.legacy_module = 'cafe' AND do2.legacy_id = co.id)
    """))
    # order_number is UNIQUE in both source tables independently (each
    # had its own ORD-YYYYMMDD-NNNN sequence per module) but NOT
    # guaranteed unique across the two combined — dining_orders.order_number
    # has a UNIQUE constraint (matching the original per-module one).
    # Resolve any real collision by disambiguating the cafe side, which
    # ran its own independent numbering — extremely unlikely in practice
    # (module + day + sequence would all have to match) but must not be
    # allowed to silently fail half the copy.
    bind.execute(sa.text("""
        UPDATE dining_orders d
        SET order_number = d.order_number || '-CAFE'
        WHERE d.legacy_module = 'cafe'
          AND EXISTS (
              SELECT 1 FROM dining_orders r
              WHERE r.legacy_module = 'restaurant' AND r.order_number = d.order_number
          )
    """))
    # client_local_id (offline-sync idempotency key) is UNIQUE in both
    # source tables independently too — copy it back in now that both
    # order tables exist, again disambiguating any cross-module collision
    # (same reasoning as order_number above).
    bind.execute(sa.text("""
        UPDATE dining_orders d
        SET client_local_id = o.client_local_id
        FROM orders o
        WHERE d.legacy_module = 'restaurant' AND d.legacy_id = o.id AND o.client_local_id IS NOT NULL
    """))
    bind.execute(sa.text("""
        UPDATE dining_orders d
        SET client_local_id = CASE
            WHEN EXISTS (SELECT 1 FROM dining_orders r WHERE r.client_local_id = co.client_local_id)
            THEN co.client_local_id || '-cafe'
            ELSE co.client_local_id
        END
        FROM cafe_orders co
        WHERE d.legacy_module = 'cafe' AND d.legacy_id = co.id AND co.client_local_id IS NOT NULL
    """))

    # ── Order items + their extras ──────────────────────────────────
    bind.execute(sa.text("""
        INSERT INTO dining_order_items (order_id, item_id, variant_id, name, unit_price, quantity, notes, status,
                                         voided_reason, voided_by, voided_at, legacy_module, legacy_id, created_at, updated_at)
        SELECT (SELECT do2.id FROM dining_orders do2 WHERE do2.legacy_module = 'restaurant' AND do2.legacy_id = oi.order_id),
               (SELECT di.id FROM dining_items di WHERE di.legacy_module = 'restaurant' AND di.legacy_id = oi.menu_item_id),
               (SELECT dv.id FROM dining_item_variants dv WHERE dv.legacy_module = 'restaurant' AND dv.legacy_id = oi.variant_id),
               oi.name, oi.unit_price, oi.quantity, oi.notes, oi.status, oi.voided_reason, oi.voided_by, oi.voided_at,
               'restaurant', oi.id, oi.created_at, oi.updated_at
        FROM order_items oi
        WHERE NOT EXISTS (SELECT 1 FROM dining_order_items doi WHERE doi.legacy_module = 'restaurant' AND doi.legacy_id = oi.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_order_items (order_id, item_id, variant_id, name, unit_price, quantity, notes, status,
                                         voided_reason, voided_by, voided_at, legacy_module, legacy_id, created_at, updated_at)
        SELECT (SELECT do2.id FROM dining_orders do2 WHERE do2.legacy_module = 'cafe' AND do2.legacy_id = coi.order_id),
               (SELECT di.id FROM dining_items di WHERE di.legacy_module = 'cafe' AND di.legacy_id = coi.item_id),
               (SELECT dv.id FROM dining_item_variants dv WHERE dv.legacy_module = 'cafe' AND dv.legacy_id = coi.variant_id),
               coi.name, coi.unit_price, coi.quantity, coi.notes, coi.status, coi.voided_reason, coi.voided_by, coi.voided_at,
               'cafe', coi.id, coi.created_at, coi.updated_at
        FROM cafe_order_items coi
        WHERE NOT EXISTS (SELECT 1 FROM dining_order_items doi WHERE doi.legacy_module = 'cafe' AND doi.legacy_id = coi.id)
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_order_item_extras (order_item_id, extra_id, extra_name, price_addition, created_at, updated_at)
        SELECT (SELECT doi.id FROM dining_order_items doi WHERE doi.legacy_module = 'restaurant' AND doi.legacy_id = oie.order_item_id),
               (SELECT de.id FROM dining_item_extras de
                  JOIN dining_item_extra_groups deg ON deg.id = de.group_id
                  WHERE deg.legacy_module = 'restaurant' AND de.name = oie.extra_name
                    AND deg.item_id = (SELECT item_id FROM dining_order_items WHERE id =
                        (SELECT doi.id FROM dining_order_items doi WHERE doi.legacy_module = 'restaurant' AND doi.legacy_id = oie.order_item_id))
                  LIMIT 1),
               oie.extra_name, oie.price_addition, oie.created_at, oie.updated_at
        FROM order_item_extras oie
        WHERE NOT EXISTS (
            SELECT 1 FROM dining_order_item_extras doie
            JOIN dining_order_items doi ON doi.id = doie.order_item_id
            WHERE doi.legacy_module = 'restaurant' AND doi.legacy_id = oie.order_item_id AND doie.extra_name = oie.extra_name
        )
    """))
    bind.execute(sa.text("""
        INSERT INTO dining_order_item_extras (order_item_id, extra_id, extra_name, price_addition, created_at, updated_at)
        SELECT (SELECT doi.id FROM dining_order_items doi WHERE doi.legacy_module = 'cafe' AND doi.legacy_id = coie.order_item_id),
               (SELECT de.id FROM dining_item_extras de
                  JOIN dining_item_extra_groups deg ON deg.id = de.group_id
                  WHERE deg.legacy_module = 'cafe' AND de.name = coie.extra_name
                    AND deg.item_id = (SELECT item_id FROM dining_order_items WHERE id =
                        (SELECT doi.id FROM dining_order_items doi WHERE doi.legacy_module = 'cafe' AND doi.legacy_id = coie.order_item_id))
                  LIMIT 1),
               coie.extra_name, coie.price_addition, coie.created_at, coie.updated_at
        FROM cafe_order_item_extras coie
        WHERE NOT EXISTS (
            SELECT 1 FROM dining_order_item_extras doie
            JOIN dining_order_items doi ON doi.id = doie.order_item_id
            WHERE doi.legacy_module = 'cafe' AND doi.legacy_id = coie.order_item_id AND doie.extra_name = coie.extra_name
        )
    """))

    # ── Kitchen tickets (historical snapshot — see DINING_CUTOVER_PLAN.md
    # for why this table doesn't get new live rows until D-05) ────────
    bind.execute(sa.text("""
        INSERT INTO dining_kitchen_tickets (branch_id, outlet_id, order_id, station, items_snapshot, status, created_at, updated_at)
        SELECT kt.branch_id,
               (SELECT out.id FROM dining_outlets out WHERE out.branch_id = kt.branch_id AND out.legacy_module = kt.module),
               (SELECT do2.id FROM dining_orders do2 WHERE do2.legacy_module = kt.module AND do2.legacy_id = kt.order_id),
               kt.station, kt.items_snapshot, kt.status, kt.created_at, kt.updated_at
        FROM kitchen_tickets kt
        WHERE kt.module IN ('restaurant', 'cafe')
          AND EXISTS (SELECT 1 FROM dining_orders do2 WHERE do2.legacy_module = kt.module AND do2.legacy_id = kt.order_id)
          -- dining_kitchen_tickets has no legacy_id (ephemeral/operational,
          -- not a financial record — see models.py docstring), so dedup
          -- here on (order, station, snapshot) instead to keep this
          -- specific copy idempotent on re-run too.
          AND NOT EXISTS (
              SELECT 1 FROM dining_kitchen_tickets existing
              WHERE existing.order_id = (SELECT do2.id FROM dining_orders do2 WHERE do2.legacy_module = kt.module AND do2.legacy_id = kt.order_id)
                AND existing.station = kt.station
                AND existing.items_snapshot::text = kt.items_snapshot::text
          )
    """))
