"""restaurant_tables_grid_cafe_payment_method_hub_pms_link

Revision ID: 5df68c547b10
Revises: b5c6d7e8f9a0
Create Date: 2026-07-10 19:20:54.085309
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5df68c547b10'
down_revision: Union[str, None] = 'b5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_date', table_name='attendance_records')
    op.create_index(op.f('ix_attendance_records_record_date'), 'attendance_records', ['record_date'], unique=False)
    op.drop_constraint('audit_logs_branch_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_beach_inventory_inventory_date'), 'beach_inventory', ['inventory_date'], unique=False)
    op.drop_index('ix_beach_reservations_date', table_name='beach_reservations')
    op.create_index(op.f('ix_beach_reservations_reservation_date'), 'beach_reservations', ['reservation_date'], unique=False)
    op.drop_index('ix_beach_tx_date', table_name='beach_transactions')
    op.create_index(op.f('ix_beach_transactions_tx_date'), 'beach_transactions', ['tx_date'], unique=False)
    op.drop_index('ix_bookings_branch_check_in', table_name='bookings')
    op.drop_index('ix_bookings_branch_status', table_name='bookings')
    op.drop_index('ix_cafe_item_recipe_lines_cafe_item_id', table_name='cafe_item_recipe_lines')
    op.drop_index('ix_cafe_item_recipe_lines_product_id', table_name='cafe_item_recipe_lines')
    op.drop_index('ix_cafe_item_variant_recipe_lines_product_id', table_name='cafe_item_variant_recipe_lines')
    op.drop_index('ix_cafe_item_variant_recipe_lines_variant_id', table_name='cafe_item_variant_recipe_lines')
    op.drop_index('ix_cafe_item_variants_cafe_item_id', table_name='cafe_item_variants')
    op.drop_index('ix_cafe_order_items_variant_id', table_name='cafe_order_items')
    op.add_column('cafe_orders', sa.Column('client_local_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'cafe_orders', ['client_local_id'])
    op.drop_index('ix_discounts_branch_active', table_name='conditional_discounts')
    op.drop_index('ix_folio_charges_folio', table_name='folio_charges')
    op.drop_index('ix_folios_branch_status', table_name='folios')
    op.drop_index('ix_housekeeping_tasks_branch', table_name='housekeeping_tasks')
    op.alter_column('hub_online_bookings', 'adults',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index('ix_menu_item_recipe_lines_menu_item_id', table_name='menu_item_recipe_lines')
    op.drop_index('ix_menu_item_recipe_lines_product_id', table_name='menu_item_recipe_lines')
    op.drop_index('ix_menu_item_variant_recipe_lines_product_id', table_name='menu_item_variant_recipe_lines')
    op.drop_index('ix_menu_item_variant_recipe_lines_variant_id', table_name='menu_item_variant_recipe_lines')
    op.drop_index('ix_menu_item_variants_menu_item_id', table_name='menu_item_variants')
    op.drop_constraint('notifications_branch_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index('ix_order_items_variant_id', table_name='order_items')
    op.add_column('orders', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.drop_index('ix_orders_branch_status', table_name='orders')
    op.drop_index('ix_rooms_branch_status', table_name='rooms')
    op.drop_constraint('settings_branch_id_fkey', 'settings', type_='foreignkey')
    op.create_foreign_key(None, 'settings', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.create_foreign_key('settings_branch_id_fkey', 'settings', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_rooms_branch_status', 'rooms', ['branch_id', 'status'], unique=False)
    op.create_index('ix_orders_branch_status', 'orders', ['branch_id', 'status'], unique=False)
    op.drop_column('orders', 'payment_method')
    op.create_index('ix_order_items_variant_id', 'order_items', ['variant_id'], unique=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_branch_id_fkey', 'notifications', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_menu_item_variants_menu_item_id', 'menu_item_variants', ['menu_item_id'], unique=False)
    op.create_index('ix_menu_item_variant_recipe_lines_variant_id', 'menu_item_variant_recipe_lines', ['variant_id'], unique=False)
    op.create_index('ix_menu_item_variant_recipe_lines_product_id', 'menu_item_variant_recipe_lines', ['product_id'], unique=False)
    op.create_index('ix_menu_item_recipe_lines_product_id', 'menu_item_recipe_lines', ['product_id'], unique=False)
    op.create_index('ix_menu_item_recipe_lines_menu_item_id', 'menu_item_recipe_lines', ['menu_item_id'], unique=False)
    op.alter_column('hub_online_bookings', 'adults',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index('ix_housekeeping_tasks_branch', 'housekeeping_tasks', ['branch_id', 'status'], unique=False)
    op.create_index('ix_folios_branch_status', 'folios', ['branch_id', 'status'], unique=False)
    op.create_index('ix_folio_charges_folio', 'folio_charges', ['folio_id'], unique=False)
    op.create_index('ix_discounts_branch_active', 'conditional_discounts', ['branch_id', 'is_active'], unique=False)
    op.drop_constraint(None, 'cafe_orders', type_='unique')
    op.drop_column('cafe_orders', 'client_local_id')
    op.create_index('ix_cafe_order_items_variant_id', 'cafe_order_items', ['variant_id'], unique=False)
    op.create_index('ix_cafe_item_variants_cafe_item_id', 'cafe_item_variants', ['cafe_item_id'], unique=False)
    op.create_index('ix_cafe_item_variant_recipe_lines_variant_id', 'cafe_item_variant_recipe_lines', ['variant_id'], unique=False)
    op.create_index('ix_cafe_item_variant_recipe_lines_product_id', 'cafe_item_variant_recipe_lines', ['product_id'], unique=False)
    op.create_index('ix_cafe_item_recipe_lines_product_id', 'cafe_item_recipe_lines', ['product_id'], unique=False)
    op.create_index('ix_cafe_item_recipe_lines_cafe_item_id', 'cafe_item_recipe_lines', ['cafe_item_id'], unique=False)
    op.create_index('ix_bookings_branch_status', 'bookings', ['branch_id', 'status'], unique=False)
    op.create_index('ix_bookings_branch_check_in', 'bookings', ['branch_id', 'check_in'], unique=False)
    op.drop_index(op.f('ix_beach_transactions_tx_date'), table_name='beach_transactions')
    op.create_index('ix_beach_tx_date', 'beach_transactions', ['branch_id', 'tx_date'], unique=False)
    op.drop_index(op.f('ix_beach_reservations_reservation_date'), table_name='beach_reservations')
    op.create_index('ix_beach_reservations_date', 'beach_reservations', ['branch_id', 'reservation_date'], unique=False)
    op.drop_index(op.f('ix_beach_inventory_inventory_date'), table_name='beach_inventory')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_branch_id_fkey', 'audit_logs', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_attendance_records_record_date'), table_name='attendance_records')
    op.create_index('ix_attendance_date', 'attendance_records', ['record_date'], unique=False)
    # ### end Alembic commands ###
