"""cash_movement_destination_cost_center_channel_pricing

Click-ERP-comparison batch (2026-07-16), 3 targeted additions — hand-written,
not autogenerated (autogenerate against this DB also wanted to drop a dozen
legacy restaurant/cafe tables and an abandoned dining_order_splits/
dining_order_payments schema; that's a separate, riskier cleanup this
migration deliberately does not touch):

1. cash_movements.destination + cost_center_id
2. dining_outlets: per-order-type service-charge overrides + delivery_fee
3. dining_orders.delivery_fee

Revision ID: 9f3c1a7e5b02
Revises: 504f42d2c755
Create Date: 2026-07-16
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '9f3c1a7e5b02'
down_revision: Union[str, None] = '504f42d2c755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('cash_movements', sa.Column('destination', sa.String(length=20), nullable=True))
    op.add_column('cash_movements', sa.Column('cost_center_id', sa.Integer(), nullable=True))
    op.create_index('ix_cash_movements_cost_center_id', 'cash_movements', ['cost_center_id'], unique=False)
    op.create_foreign_key(
        'fk_cash_movements_cost_center_id', 'cash_movements', 'cost_centers',
        ['cost_center_id'], ['id'], ondelete='SET NULL',
    )

    op.add_column('dining_outlets', sa.Column('takeaway_service_charge_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('dining_outlets', sa.Column('delivery_service_charge_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('dining_outlets', sa.Column('room_service_service_charge_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('dining_outlets', sa.Column('delivery_fee', sa.Numeric(precision=8, scale=2), nullable=True))

    op.add_column('dining_orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.alter_column('dining_orders', 'delivery_fee', server_default=None)


def downgrade() -> None:
    op.drop_column('dining_orders', 'delivery_fee')

    op.drop_column('dining_outlets', 'delivery_fee')
    op.drop_column('dining_outlets', 'room_service_service_charge_pct')
    op.drop_column('dining_outlets', 'delivery_service_charge_pct')
    op.drop_column('dining_outlets', 'takeaway_service_charge_pct')

    op.drop_constraint('fk_cash_movements_cost_center_id', 'cash_movements', type_='foreignkey')
    op.drop_index('ix_cash_movements_cost_center_id', table_name='cash_movements')
    op.drop_column('cash_movements', 'cost_center_id')
    op.drop_column('cash_movements', 'destination')
