"""Add unit_cost/total_cost to utility_readings (Task B analytics audit)

resort-os-docs/06-MODULES.md § ANALYTICS spec describes UtilityReading as
"type (electricity/water/gas/diesel)، period (YYYY-MM)، consumption، unit_cost،
total_cost → JournalEntry تلقائي" — the original migration
(c9f1a852_new_models.py) created utility_readings with reading_value/unit/notes
but never added unit_cost/total_cost, so there was no way to record the cost
side of a utility reading at all (and thus no way to post the journal entry the
spec describes, or compute the "Energy" KPI). Hand-written (not autogenerated)
to avoid picking up unrelated drift from concurrent work in other modules this
session, per the project's own migration-hygiene note.

Revision ID: analytics_util_cost
Revises: fix_ts_defaults
Create Date: 2026-07-01
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "analytics_util_cost"
down_revision: Union[str, None] = "fix_ts_defaults"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "utility_readings",
        sa.Column("unit_cost", sa.Numeric(10, 2), nullable=False, server_default="0"),
    )
    op.add_column(
        "utility_readings",
        sa.Column("total_cost", sa.Numeric(12, 2), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    op.drop_column("utility_readings", "total_cost")
    op.drop_column("utility_readings", "unit_cost")
