"""new_models_phase2

Revision ID: c9f1a852
Revises: b7e2d415
Create Date: 2026-06-30 12:00:00

New tables:
  PMS:       housekeeping_tasks, rate_plans
  Timeshare: timeshare_visits
  Leasing:   tenant_cash_logs
  Analytics: daily_stats, guest_reviews, review_categories, utility_readings
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision      = "c9f1a852"
down_revision = "b7e2d415"
branch_labels = None
depends_on    = None


def upgrade() -> None:

    # ── PMS: housekeeping_tasks ───────────────────────────────────────
    op.create_table(
        "housekeeping_tasks",
        sa.Column("id",           sa.Integer(),    nullable=False),
        sa.Column("branch_id",    sa.Integer(),    nullable=False),
        sa.Column("room_id",      sa.Integer(),    nullable=False),
        sa.Column("assigned_to",  sa.Integer(),    nullable=True),
        sa.Column("task_type",    sa.String(30),   nullable=False, server_default="checkout_clean"),
        sa.Column("status",       sa.String(30),   nullable=False, server_default="dirty"),
        sa.Column("priority",     sa.String(10),   nullable=False, server_default="normal"),
        sa.Column("notes",        sa.Text(),       nullable=True),
        sa.Column("started_at",   sa.DateTime(),   nullable=True),
        sa.Column("completed_at", sa.DateTime(),   nullable=True),
        sa.Column("created_at",   sa.DateTime(),   nullable=True),
        sa.Column("updated_at",   sa.DateTime(),   nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"],   ["rooms.id"],    ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_housekeeping_tasks_branch", "housekeeping_tasks", ["branch_id", "status"])

    # ── PMS: rate_plans ───────────────────────────────────────────────
    op.create_table(
        "rate_plans",
        sa.Column("id",                   sa.Integer(),       nullable=False),
        sa.Column("branch_id",            sa.Integer(),       nullable=False),
        sa.Column("room_type_id",         sa.Integer(),       nullable=True),
        sa.Column("name",                 sa.String(100),     nullable=False),
        sa.Column("name_ar",              sa.String(100),     nullable=True),
        sa.Column("base_rate_override",   sa.Numeric(10, 2),  nullable=True),
        sa.Column("rate_multiplier",      sa.Numeric(6, 4),   nullable=False, server_default="1.0000"),
        sa.Column("valid_from",           sa.Date(),          nullable=False),
        sa.Column("valid_until",          sa.Date(),          nullable=False),
        sa.Column("seasonal_adjustments", sa.Text(),          nullable=True),
        sa.Column("min_nights",           sa.Integer(),       nullable=False, server_default="1"),
        sa.Column("is_active",            sa.Boolean(),       nullable=False, server_default="true"),
        sa.Column("created_at",           sa.DateTime(),      nullable=True),
        sa.Column("updated_at",           sa.DateTime(),      nullable=True),
        sa.ForeignKeyConstraint(["branch_id"],    ["branches.id"],    ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_type_id"], ["room_types.id"],  ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # NOTE: timeshare_visits and tenant_cash_logs were originally created here,
    # but they FK-reference timeshare_contracts / lease_contracts which were
    # never migrated. Both tables are recreated (in correct dependency order,
    # alongside their parent tables) by a later autogenerated migration.

    # ── Analytics: daily_stats ────────────────────────────────────────
    op.create_table(
        "daily_stats",
        sa.Column("id",                 sa.Integer(),      nullable=False),
        sa.Column("branch_id",          sa.Integer(),      nullable=False),
        sa.Column("stat_date",          sa.Date(),         nullable=False, index=True),
        sa.Column("occupied_rooms",     sa.Integer(),      nullable=False, server_default="0"),
        sa.Column("total_rooms",        sa.Integer(),      nullable=False, server_default="0"),
        sa.Column("occupancy_pct",      sa.Numeric(5, 2),  nullable=False, server_default="0"),
        sa.Column("adr",                sa.Numeric(10, 2), nullable=False, server_default="0"),
        sa.Column("revpar",             sa.Numeric(10, 2), nullable=False, server_default="0"),
        sa.Column("room_revenue",       sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("beach_visitors",     sa.Integer(),      nullable=False, server_default="0"),
        sa.Column("beach_revenue",      sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("restaurant_covers",  sa.Integer(),      nullable=False, server_default="0"),
        sa.Column("restaurant_revenue", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("cafe_revenue",       sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("total_revenue",      sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("generated_at",       sa.DateTime(),     nullable=True),
        sa.Column("created_at",         sa.DateTime(),     nullable=True),
        sa.Column("updated_at",         sa.DateTime(),     nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── Analytics: guest_reviews ──────────────────────────────────────
    op.create_table(
        "guest_reviews",
        sa.Column("id",             sa.Integer(),  nullable=False),
        sa.Column("branch_id",      sa.Integer(),  nullable=False),
        sa.Column("booking_id",     sa.Integer(),  nullable=True),
        sa.Column("guest_name",     sa.String(200),nullable=False),
        sa.Column("overall_rating", sa.Integer(),  nullable=False),
        sa.Column("comment",        sa.Text(),     nullable=True),
        sa.Column("source",         sa.String(30), nullable=False, server_default="direct"),
        sa.Column("is_published",   sa.Boolean(),  nullable=False, server_default="true"),
        sa.Column("reviewed_at",    sa.Date(),     nullable=False),
        sa.Column("created_at",     sa.DateTime(), nullable=True),
        sa.Column("updated_at",     sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"],  ["branches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── Analytics: review_categories ─────────────────────────────────
    op.create_table(
        "review_categories",
        sa.Column("id",         sa.Integer(),  nullable=False),
        sa.Column("review_id",  sa.Integer(),  nullable=False),
        sa.Column("category",   sa.String(30), nullable=False),
        sa.Column("rating",     sa.Integer(),  nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["review_id"], ["guest_reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── Analytics: utility_readings ───────────────────────────────────
    op.create_table(
        "utility_readings",
        sa.Column("id",            sa.Integer(),      nullable=False),
        sa.Column("branch_id",     sa.Integer(),      nullable=False),
        sa.Column("reading_date",  sa.Date(),         nullable=False, index=True),
        sa.Column("utility_type",  sa.String(20),     nullable=False),
        sa.Column("reading_value", sa.Numeric(12, 3), nullable=False),
        sa.Column("unit",          sa.String(10),     nullable=False, server_default="kWh"),
        sa.Column("notes",         sa.String(300),    nullable=True),
        sa.Column("recorded_by",   sa.Integer(),      nullable=True),
        sa.Column("created_at",    sa.DateTime(),     nullable=True),
        sa.Column("updated_at",    sa.DateTime(),     nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("utility_readings")
    op.drop_table("review_categories")
    op.drop_table("guest_reviews")
    op.drop_table("daily_stats")
    op.drop_table("rate_plans")
    op.drop_index("ix_housekeeping_tasks_branch", table_name="housekeeping_tasks")
    op.drop_table("housekeeping_tasks")
